{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "mylibrary",
    "version": "1.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "bc2o4dazn5behbjtnwkwbnxejq"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mylibrary-1.3.4.aar",
          "url": "mylibrary-1.3.4.aar",
          "size": 235412,
          "sha512": "46639074770179bd0b55044e2648f971b578a38f52029b2ab440a2b118bc30229c5bc3252588fd77c3f0124dbc9471ee77aefcaf908bc1b98fbb43cd3c4dba43",
          "sha256": "6c9e772965728fa7ec8dc10dacfe25eb03933d0a0bb0a69e5676024322cccae0",
          "sha1": "1f1f2f50ccda73f087ec6e38d6d33f6a4258f00e",
          "md5": "da20ab2f6e4af5aa5b633a5f8e78f6df"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.print",
          "module": "print",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "mylibrary-1.3.4.aar",
          "url": "mylibrary-1.3.4.aar",
          "size": 235412,
          "sha512": "46639074770179bd0b55044e2648f971b578a38f52029b2ab440a2b118bc30229c5bc3252588fd77c3f0124dbc9471ee77aefcaf908bc1b98fbb43cd3c4dba43",
          "sha256": "6c9e772965728fa7ec8dc10dacfe25eb03933d0a0bb0a69e5676024322cccae0",
          "sha1": "1f1f2f50ccda73f087ec6e38d6d33f6a4258f00e",
          "md5": "da20ab2f6e4af5aa5b633a5f8e78f6df"
        }
      ]
    }
  ]
}
